import { useEffect, useRef, useState } from "react";
import { generate, move, reset, type Direction, type GenerationSuccess } from "../engine/index.js";
import type { RawSettings } from "../../domain-foundation/index.js";
import "./style.css";

const defaults: RawSettings = { width: 32, height: 24, seedInput: "", minRoomWidth: 3, minRoomHeight: 3, maxRoomWidth: 8, maxRoomHeight: 8, corridorWidth: 1, minPathLength: 5, maxDeadEnds: 10 };
const directionFor = (key: string): Direction | undefined => ({ ArrowUp: "north", w: "north", W: "north", ArrowDown: "south", s: "south", S: "south", ArrowLeft: "west", a: "west", A: "west", ArrowRight: "east", d: "east", D: "east" })[key] as Direction | undefined;

export function App(): JSX.Element {
  const [settings, setSettings] = useState(defaults); const [result, setResult] = useState<GenerationSuccess>(); const [message, setMessage] = useState("Choose a seed or use the defaults, then generate."); const canvas = useRef<HTMLCanvasElement>(null);
  const generateDungeon = () => { const outcome = generate(settings); if (outcome.ok) { setResult(outcome.value); setMessage(`Generated seed: ${outcome.value.seed}`); } else setMessage(outcome.error.map(error => error.message).join(" ")); };
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement) return; const direction = directionFor(event.key); if (!direction || !result) return; event.preventDefault(); const session = move(result.dungeon, result.session, direction); setResult({ ...result, session }); if (session.completed) setMessage("You reached the exit!"); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [result]);
  useEffect(() => { const element = canvas.current; if (!element || !result) return; const { dungeon, session } = result; const scale = Math.max(12, Math.min(28, Math.floor(640 / Math.max(dungeon.dimensions.width, dungeon.dimensions.height)))); element.width = dungeon.dimensions.width * scale; element.height = dungeon.dimensions.height * scale; const context = element.getContext("2d"); if (!context) return; dungeon.tiles.forEach((row, y) => row.forEach((tile, x) => { const drawY = dungeon.dimensions.height - 1 - y; context.fillStyle = tile.terrain === "walkable" ? "#f5e9c9" : "#1e2430"; context.fillRect(x * scale, drawY * scale, scale, scale); if (tile.marker === "entrance") { context.fillStyle = "#3b82f6"; context.fillRect(x * scale + scale / 4, drawY * scale + scale / 4, scale / 2, scale / 2); } if (tile.marker === "exit") { context.fillStyle = "#22c55e"; context.fillRect(x * scale + scale / 4, drawY * scale + scale / 4, scale / 2, scale / 2); } })); context.fillStyle = "#ef4444"; context.beginPath(); context.arc((session.position.x + .5) * scale, (dungeon.dimensions.height - session.position.y - .5) * scale, scale * .28, 0, Math.PI * 2); context.fill(); }, [result]);
  return <main><h1>Dungeon Generator POC</h1><section className="controls"><label>Seed <input data-testid="poc-seed-input" value={settings.seedInput} onChange={event => setSettings({ ...settings, seedInput: event.target.value })} /></label><label>Width <input data-testid="poc-width-input" type="number" value={settings.width} onChange={event => setSettings({ ...settings, width: Number(event.target.value) })} /></label><label>Height <input data-testid="poc-height-input" type="number" value={settings.height} onChange={event => setSettings({ ...settings, height: Number(event.target.value) })} /></label><button data-testid="poc-generate-button" onClick={generateDungeon}>Generate</button><button data-testid="poc-reset-button" disabled={!result} onClick={() => result && setResult({ ...result, session: reset(result.dungeon) })}>Reset</button></section><p data-testid="poc-status" role="status">{message}</p><canvas ref={canvas} aria-label="Generated dungeon map" /></main>;
}
